services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_backend
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    depends_on:
      - db

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: laravel_frontend
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "127.0.0.1:3000:3000"  # ここはホットリロードのポートに合わせて変更
    depends_on:
      - app

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "127.0.0.1:443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../ssl/localhost.pem:/etc/nginx/ssl/localhost.pem
      - ../ssl/localhost-key.pem:/etc/nginx/ssl/localhost-key.pem
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minesweaper
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: